{* position actuelle *}
{def $menuArray=array()}{foreach $module_result.path as $path}{if $path.url|is_string}{if $path.url_alias|is_string}{set $menuArray=$menuArray|insert(0,$path.node_id)|reverse}{else}{set $menuArray=$menuArray|insert(0,$path.node_id)|reverse}{/if}{else}{set $menuArray=$menuArray|insert(0,$path.node_id)|reverse}{/if}{/foreach}
{* Début *}
{if $sid|eq(16)}{def $childrenTmp = fetch( 'content', 'node', hash( 'node_id', $site_node_id))}{def $children=array($childrenTmp)}{else}

{def $children = fetch( 'content', 'list',hash( 'parent_node_id', 2,'class_filter_type', 'include','class_filter_array', array( 'bouygues_master_page','bouygues_liste' ),'attribute_filter',array(array('section','=',$sid)),'sort_by', array( array( 'priority' ) )))}
{/if}

{def $i=1 $n2=true() $jsN2=false() $linkN2=false() $listOn=0 $count_children=0 $sub_children=''}{def $sub_sub_children = ''}{def $sub_sub_sub_children = ''}{def $sub_sub_sub_sub_children = ''}{def $sub_sub_sub_sub_sub_children = ''}{def $sub_sub_sub_sub_sub_sub_children = ''}{def $sub_sub_sub_sub_sub_sub_sub_children = ''}
{if is_set($external_link)|not()}{def $external_link=''}{/if}

{if gt($children|count(),0)}
	   <!-- Niv 1 : filière (invisible pour l'utilisateur)-->    
		{foreach $children as $Child}{set $sub_children = fetch('content','list',hash( 'parent_node_id', $Child.node_id,'class_filter_type','include', 'class_filter_array', array( 'bouygues_page_sessions','article','bouygues_diapo','bouygues_dossier','bouygues_galerie_vid','bouygues_liste','bouygues_liste_thema','bouygues_mini_site','bougues_video','bouygues_categorie', 'bouygues_whoswho_search', 'bouygues_whoswho_list', 'link' ), 'sort_by', array( array( 'priority' ) )))}{foreach $sub_children as $node_children}{if or($node_children.data_map.menu_cb.value|eq(1), $node_children.class_identifier|eq('bouygues_categorie'))}{set $count_children=$count_children|inc}{/if}{/foreach}
		    <ul id="lmenu" class="{$arrCssSubStructure[$Child.object.section_id]}">
	       	  <!-- Niv 2 : premiers éléments d'une filière-->
	       	 <li><a href="{$Child.url_alias|ezurl(no)}" class="linkOff-noArrow colorDefault1 border4">{"accueil menu"|i18n("design/bouygues/master")}</a></li> {foreach $sub_children as $Sub_child}{if or($Sub_child.data_map.menu_cb.value|eq(1), $Sub_child.class_identifier|eq('bouygues_categorie'), $Sub_child.class_identifier|eq('link'))}{set $sub_sub_children = fetch('content','list',hash('parent_node_id', $Sub_child.node_id,'class_filter_type','include', 'class_filter_array', array( 'bouygues_page_sessions','article','bouygues_diapo','bouygues_dossier','bouygues_galerie_vid','bouygues_liste','bouygues_liste_thema','bouygues_mini_site','bougues_video','bouygues_categorie', 'bouygues_whoswho_search', 'bouygues_whoswho_list', 'link' ), 'sort_by', array( array( 'priority' ) )))}{*Ouvrir les enfants ?*}{if is_set($Sub_child.data_map.menu_se_cb)}{if $Sub_child.data_map.menu_se_cb.value|eq(1)}{set $n2=true()}{else}{set $n2=false()}{/if}{else}{set $n2=true()}{/if}{if $n2}{set $count_children=0}{foreach $sub_sub_children as $node_children}{if or($node_children.data_map.menu_cb.value|eq(1), $node_children.class_identifier|eq('bouygues_categorie'))}{set $count_children=$count_children|inc}{/if}{/foreach}{else}{set $count_children=0}{/if}{*Gestion des catégories ?*}{set $jsN2=false()}{set $linkN2=false()}{if is_set($Sub_child.data_map.menu_1se_select)}{if $Sub_child.data_map.menu_1se_select.value.0|eq(1)}{set $jsN2=true()}{else}{set $linkN2=true()}{/if}{/if}{*Gestion des liens externes ?*}{if $Sub_child.class_identifier|eq('link')}{set $external_link=$Sub_child.data_map.lien.content|ezurl(no)}{else}{set $external_link=false()}{/if}
		  			<li class="{if $jsN2}show-next-level{/if}{if and($menuArray|contains($Sub_child.node_id),$count_children|gt(0))} bgColor3 listOn{/if}" ><a href="{if eq($external_link, false())|not()}{$external_link}{elseif $linkN2}{$Sub_child.children.0.url_alias|ezurl(no)}{else}{$Sub_child.url_alias|ezurl(no)}{/if}" class="{if $menuArray|contains($Sub_child.node_id)} bgColor4 color1 {if $count_children|gt(0)}linkOn{else}linkOn-noArrow{/if} {elseif lt($count_children,1)} linkOff-noArrow colorDefault1 border4 {else}linkOff colorDefault1 border4{/if}" {if $jsN2} onclick="return false;" {/if} {if eq($external_link, false())|not()}target="_blank"{/if} title="{if and(eq($external_link, false())|not(),$Sub_child.data_map.lien.data_text)}{$Sub_child.data_map.lien.data_text}{else}{$Sub_child.name|upfirst}{/if}">{if eq($external_link, false())|not()}{$Sub_child.data_map.lien.data_text}{else}{$Sub_child.name|upfirst}{/if}</a>{if and(gt($count_children,0),$n2)}  
		             	<ul class="{if $menuArray|contains($Sub_child.node_id)|not}displayNone {/if}">
		             	 <!-- Niv 3 -->{def $max_subchildren = $count_children}{def $count_subchildren = 1}{foreach $sub_sub_children as $sub_sub_child}	{if or($sub_sub_child.data_map.menu_cb.value|eq(1), $sub_sub_child.class_identifier|eq('bouygues_categorie'), $Sub_child.class_identifier|eq('link'))}{set $sub_sub_sub_children = fetch( 'content', 'list',hash( 'parent_node_id', $sub_sub_child.node_id,'class_filter_type','include', 'class_filter_array', array( 'bouygues_page_sessions','article','bouygues_diapo','bouygues_dossier','bouygues_galerie_vid','bouygues_liste','bouygues_liste_thema','bouygues_mini_site','bougues_video','bouygues_categorie', 'bouygues_whoswho_search', 'bouygues_whoswho_list', 'link' ), 'sort_by', array( array( 'priority' ) )))}{*Ouvrir les enfants ?*}{if is_set($sub_sub_child.data_map.menu_se_cb)}{if $sub_sub_child.data_map.menu_se_cb.value|eq(1)}{set $n2=true()}{else}{set $n2=false()}{/if}{else}{set $n2=true()}{/if}{if $n2}{set $count_children=0}{foreach $sub_sub_sub_children as $node_children}{if or($node_children.data_map.menu_cb.value|eq(1), $node_children.class_identifier|eq('bouygues_categorie'))}{set $count_children=$count_children|inc}{/if}{/foreach}{else}{set $count_children=0}{/if}{*Gestion des catégories ?*}{set $jsN2=false()}{set $linkN2=false()}{if is_set($sub_sub_child.data_map.menu_1se_select)}{if $sub_sub_child.data_map.menu_1se_select.value.0|eq(1)}{set $jsN2=true()}{else}{set $linkN2=true()}{/if}{/if}{*Gestion des liens externes ?*}{if $sub_sub_child.class_identifier|eq('link')}{set $external_link=$sub_sub_child.data_map.lien.content|ezurl(no)}{else}{set $external_link=false()}{/if}
		             		<li class="{if $jsN2}show-next-level{/if}"><a href="{if eq($external_link, false())|not()}{$external_link}{elseif $linkN2}{$sub_sub_child.children.0.url_alias|ezurl(no)}{else}{$sub_sub_child.url_alias|ezurl(no)}{/if}" {if $jsN2} onclick="return false;" {/if} class="{if $menuArray|contains($sub_sub_child.node_id)} {if $count_children|gt(0)}sbLinkOn{else}sbLinkOn-noArrow{/if} color1 border4 {else} colorDefault2  {/if} {if lt($count_children,1)}noArrow{/if} {if $count_subchildren|lt($max_subchildren)}border4{/if}" {if eq($external_link, false())|not()}target="_blank"{/if} title="{if and(eq($external_link, false())|not(),$sub_sub_child.data_map.lien.data_text)}{$sub_sub_child.data_map.lien.data_text}{else}{$sub_sub_child.name|upfirst}{/if}">{if and(eq($external_link, false())|not(),$sub_sub_child.data_map.lien.data_text)}{$sub_sub_child.data_map.lien.data_text}{else}{$sub_sub_child.name|upfirst}{/if}</a>{if and(gt($count_children,0),$n2)}     
			<ul class="{if $menuArray|contains($sub_sub_child.node_id)|not}displayNone{/if}"><!-- Niv 4 -->	{def $max_subsubchildren = $count_children}{def $count_subsubchildren = 1}{foreach $sub_sub_sub_children as $sub_sub_sub_child}	{if or($sub_sub_sub_child.data_map.menu_cb.value|eq(1), $sub_sub_sub_child.class_identifier|eq('bouygues_categorie'), $Sub_child.class_identifier|eq('link'))}{set $sub_sub_sub_sub_children = fetch( 'content', 'list',hash( 'parent_node_id', $sub_sub_sub_child.node_id,'class_filter_type','include', 'class_filter_array', array( 'bouygues_page_sessions','article','bouygues_diapo','bouygues_dossier','bouygues_galerie_vid','bouygues_liste','bouygues_liste_thema','bouygues_mini_site','bougues_video','bouygues_categorie', 'bouygues_whoswho_search', 'bouygues_whoswho_list', 'link' ), 'sort_by', array( array( 'priority' ) )))}{*Ouvrir les enfants ?*}{if is_set($sub_sub_sub_child.data_map.menu_se_cb)}{if $sub_sub_sub_child.data_map.menu_se_cb.value|eq(1)}{set $n2=true()}{else}{set $n2=false()}{/if}{else}{set $n2=true()}{/if}{if $n2}{set $count_children=0}{foreach $sub_sub_sub_sub_children as $node_children}{if or($node_children.data_map.menu_cb.value|eq(1), $node_children.class_identifier|eq('bouygues_categorie'))}{set $count_children=$count_children|inc}{/if}{/foreach}{else}{set $count_children=0}{/if}{*Gestion des catégories ?*}{set $jsN2=false()}{set $linkN2=false()}{if is_set($sub_sub_sub_child.data_map.menu_1se_select)}{if $sub_sub_sub_child.data_map.menu_1se_select.value.0|eq(1)}{set $jsN2=true()}{else}{set $linkN2=true()}{/if}{/if}{*Gestion des liens externes ?*}{if $sub_sub_sub_child.class_identifier|eq('link')}{set $external_link=$sub_sub_sub_child.data_map.lien.content|ezurl(no)}{else}{set $external_link=false()}{/if}
									<li class="{if $jsN2}show-next-level{/if}"><a href="{if eq($external_link, false())|not()}{$external_link}{elseif $linkN2}{$sub_sub_sub_child.children.0.url_alias|ezurl(no)}{else}{$sub_sub_sub_child.url_alias|ezurl(no)}{/if}" {if $jsN2} onclick="return false;" {/if} class="{if $menuArray|contains($sub_sub_sub_child.node_id)} {if $count_children|gt(0)}sbLinkOn border4{else}sbLinkOn-noArrow{/if} color1 {else} colorDefault2 {/if} {if lt($count_children,1)}noArrow{/if} {if $count_subsubchildren|eq($max_subsubchildren)}border4{/if}" {if eq($external_link, false())|not()}target="_blank"{/if} title="{if and(eq($external_link, false())|not(),$sub_sub_sub_child.data_map.lien.data_text)}{$sub_sub_sub_child.data_map.lien.data_text}{else}{$sub_sub_sub_child.name|upfirst}{/if}">{if and(eq($external_link, false())|not(),$sub_sub_sub_child.data_map.lien.data_text)}{$sub_sub_sub_child.data_map.lien.data_text}{else}{$sub_sub_sub_child.name|upfirst}{/if}</a>{if and(gt($count_children,0),$n2)} 
											<ul class="{if $menuArray|contains($sub_sub_sub_child.node_id)|not}displayNone{/if}"><!-- Niv 5 -->{def $max_subsubsubchildren = $count_children}{def $count_subsubsubchildren = 1}{foreach $sub_sub_sub_sub_children as $sub_sub_sub_sub_child}{if or($sub_sub_sub_sub_child.data_map.menu_cb.value|eq(1), $sub_sub_sub_sub_child.class_identifier|eq('bouygues_categorie'), $Sub_child.class_identifier|eq('link'))}{set $sub_sub_sub_sub_sub_children = fetch( 'content', 'list',hash( 'parent_node_id', $sub_sub_sub_sub_child.node_id,'class_filter_type','include', 'class_filter_array', array( 'bouygues_page_sessions','article','bouygues_diapo','bouygues_dossier','bouygues_galerie_vid','bouygues_liste','bouygues_liste_thema','bouygues_mini_site','bougues_video','bouygues_categorie', 'bouygues_whoswho_search', 'bouygues_whoswho_list', 'link' ), 'sort_by', array( array( 'priority' ) )))}{*Ouvrir les enfants ?*}{if is_set($sub_sub_sub_sub_child.data_map.menu_se_cb)}{if $sub_sub_sub_sub_child.data_map.menu_se_cb.value|eq(1)}{set $n2=true()}{else}{set $n2=false()}{/if}{else}{set $n2=true()}{/if}{if $n2}{set $count_children=0}{foreach $sub_sub_sub_sub_sub_children as $node_children}{if or($node_children.data_map.menu_cb.value|eq(1), $node_children.class_identifier|eq('bouygues_categorie'))}{set $count_children=$count_children|inc}{/if}{/foreach}{else}{set $count_children=0}{/if}{*Gestion des cat√©gories ?*}{set $jsN2=false()}{set $linkN2=false()}{if is_set($sub_sub_sub_sub_child.data_map.menu_1se_select)}{if $sub_sub_sub_sub_child.data_map.menu_1se_select.value.0|eq(1)}{set $jsN2=true()}{else}{set $linkN2=true()}{/if}{/if}{*Gestion des liens externes ?*}{if $sub_sub_sub_sub_child.class_identifier|eq('link')}{set $external_link=$sub_sub_sub_sub_child.data_map.lien.content|ezurl(no)}{else}{set $external_link=false()}{/if}
														<li class="{if $jsN2}show-next-level{/if}">
														<a href="{if eq($external_link, false())|not()}{$external_link}{elseif $linkN2}{$sub_sub_sub_sub_child.children.0.url_alias|ezurl(no)}{else}{$sub_sub_sub_sub_child.url_alias|ezurl(no)}{/if}" class="{if $menuArray|contains($sub_sub_sub_sub_child.node_id)} {if $count_children|gt(0)}sbLinkOn border4{else}sbLinkOn-noArrow{/if} color1 {else} colorDefault2 {/if} {if lt($count_children,1)}noArrow{/if} {if $count_subsubsubchildren|eq($max_subsubsubchildren)}border4{/if}" {if eq($external_link, false())|not()}target="_blank"{/if} title="{if and(eq($external_link, false())|not(),$sub_sub_sub_sub_child.data_map.lien.data_text)}{$sub_sub_sub_sub_child.data_map.lien.data_text}{else}{$sub_sub_sub_sub_child.name|upfirst}{/if}">{if eq($external_link, false())|not()}{$sub_sub_sub_sub_child.data_map.lien.data_text}{else}{$sub_sub_sub_sub_child.name|upfirst}{/if}</a>{if and(gt($count_children,0),$n2)} 
															<ul class="{if $menuArray|contains($sub_sub_sub_sub_child.node_id)|not}displayNone{/if}">{foreach $sub_sub_sub_sub_sub_children as $sub_sub_sub_sub_sub_child}
																	<li><a href="{$sub_sub_sub_sub_sub_child.url_alias|ezurl(no)}" class="{if $menuArray|contains($sub_sub_sub_sub_sub_child.node_id)} {if $count_children|gt(0)}sbLinkOn-noArrow{else}sbLinkOn-noArrow{/if} color1{else} colorDefault2 {/if} noArrow" title="{if and(eq($external_link, false())|not(),$sub_sub_sub_sub_sub_child.data_map.lien.data_text)}{$sub_sub_sub_sub_sub_child.data_map.lien.data_text}{else}{$sub_sub_sub_sub_sub_child.name|upfirst}{/if}" >{if and(eq($external_link, false())|not(),$sub_sub_sub_sub_sub_child.data_map.lien.data_text)}{$sub_sub_sub_sub_sub_child.data_map.lien.data_text}{else}{$sub_sub_sub_sub_sub_child.name|upfirst}{/if}</a></li>{/foreach}
															</ul>{/if}
														</li>{set $count_subsubsubchildren=inc($count_subsubsubchildren)}{/if}{/foreach}
											</ul>{/if}  
									 </li>{set $count_subsubchildren=inc($count_subsubchildren)}{/if}{/foreach}{undef $max_subsubchildren}{undef $count_subsubchildren}
		             			</ul>{/if}
		             			 <!-- Niv 4 -->	
		             		</li>{set $count_subchildren=inc($count_subchildren)}{/if}{/foreach}{undef $max_subchildren}{undef $count_subchildren}
		             	<!-- Niv 3 -->	
		             	</ul>{/if}
		  			</li>{/if}{/foreach}
	  		 <!-- Niv 2 -->
	  		</ul>
	       <!--</li>-->{set $i = inc($i)}{/foreach}{undef $i}{undef $n2}{undef $count_children}{undef $children}{undef $sub_children}{undef $sub_sub_children}{undef $sub_sub_sub_children}{undef $sub_sub_sub_sub_children}{undef $sub_sub_sub_sub_sub_children}{undef $sub_sub_sub_sub_sub_sub_children}{undef $sub_sub_sub_sub_sub_sub_sub_children}
	<!-- Niv 1 -->
	  <!--</ul>-->{/if}
<br />