{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute'
         html_class='full'}

{literal}
<script type="text/javascript">
<!-- Begin
function textCounter(field,cntfield,maxlimit) {
if (field.value.length > maxlimit) // if too long...trim it!
field.value = field.value.substring(0, maxlimit);
// otherwise, update 'characters left' counter
else
cntfield.value = maxlimit - field.value.length;
}
//  End -->
</script>
{/literal}

<textarea class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )}" name="{$attribute_base}_data_text_{$attribute.id}" cols="70" rows="{$attribute.contentclass_attribute.data_int1}"
onKeyDown="textCounter(document.editform.{$attribute_base}_data_text_{$attribute.id},document.editform.remLen1,160)"
onKeyUp="textCounter(document.editform.{$attribute_base}_data_text_{$attribute.id},document.editform.remLen1,160)"
>{$attribute.content|wash}</textarea>

<input readonly type="text" name="remLen1" size="3" maxlength="3" value="160">

{/default}
