{include uri="design:emails/global/header.tpl"}
    				
    				<table style="border-left: 1px solid #efefef; border-right: 1px solid #efefef" width="572px;" align="center" CELLSPACING="0" CELLPADDING="0">
    					<tr><td style="padding: 5px 15px 15px 15px; font-size: 12px; line-height: 1.5em">

simple digest<br/>
{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{set-block scope=root variable=subject}{'[%sitename] Digest for %date'
                                        |i18n("design/standard/notification",,
                                              hash('%date',currentdate()|l10n(datetime),
                                                   '%sitename',ezini("SiteSettings","SiteURL")))}{/set-block}
{"This email is to inform you on news at %sitename."
 |i18n('design/standard/notification',,
       hash('%sitename',ezini("SiteSettings","SiteURL")))}


{"If you do not want to continue receiving these notifications,
change your settings at:"|i18n('design/standard/notification')}
http://{ezini("SiteSettings","SiteURL")}{concat("notification/settings/")|ezurl(no)}

--
{"%sitename notification system"
 |i18n('design/standard/notification',,
       hash('%sitename',ezini("SiteSettings","SiteURL")))}

    					</td></tr>
    				</table>
    			
{include uri="design:emails/global/footer.tpl"}